EXCEL:
  file_dir: ''
  first_delay_col_index: 5
  first_student_row_index: 3
  first_question_col_index: 5
  grade_cols: []
  question_col_length: 5
  student_IDs_col_index: 3
  worksheet_name: ''
GENERAL:
  credentials_dir: 'credentials.json'
  number_of_questions: 10
  number_of_students: 200
  set_delay: true
  set_score: true
  use_grade_col_list_excel: false
  use_grade_col_list_sheet: false
SHEET:
  first_delay_col_index: 5
  first_student_row_index: 3
  first_question_col_index: 5
  grade_cols: []
  question_col_length: 5
  sheet_name: 'FOP S2021'
  student_IDs_col_index: 3
  worksheet_name: 'HW0'
